version: '3.1'

services:
  springboot:
    image: vidhucap/spring-boot-mongo:6
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb123
    ports:
      - 8080:8080
    working_dir: /opt/app
    networks:
    - springappnetwork  
    
  mongo:
    image: mongo
    container_name: springboot-mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb123
    volumes:
      - mongobkp:/data/db
          - mongoconfig:/data/config
    restart: always
    networks:
    - springappnetwork
    
volumes:
  mongobkp:
    driver: local
    
networks:
  springappnetwork:
    driver: bridge
